Repository OngDev/course-manager, pull requests merged in 2021-06, with the labels that each got.

#90 Add default layout
  packages/client/components/Globals/Logo/index.module.css
  packages/client/components/Globals/Logo/index.tsx
  packages/client/components/Layouts/Header/index.module.css
  packages/client/components/Layouts/Header/index.tsx
  packages/client/components/Layouts/Sidebar/index.module.css
  packages/client/components/Layouts/Sidebar/index.tsx
  packages/client/components/Layouts/Sidebar/sidebars.ts
  packages/client/components/Layouts/index.module.css
  packages/client/components/Layouts/index.tsx
  packages/client/components/Video/VideoList/courses.ts
  packages/client/components/Video/VideoList/index.tsx
  packages/client/constants/icons.ts
  packages/client/pages/course.tsx
  packages/client/pages/index.tsx
  packages/client/public/icons/dots.svg
  packages/client/public/icons/home.svg
  packages/client/public/icons/logo.svg
  packages/client/public/icons/message.svg
  packages/client/public/icons/profile.svg
  packages/client/public/icons/progress.svg
  packages/client/public/icons/search.svg
  packages/client/public/icons/setting.svg
  packages/client/styles/Video.module.css
  packages/client/styles/globals.css
Labels: enhancement, frontend

#93 Add login components
  packages/client/components/Login/index.module.css
  packages/client/components/Login/index.tsx
Labels: frontend

#95 Feature/auth with cookie
  packages/client/components/Login/index.tsx
  packages/client/components/Register/index.tsx
  packages/client/package.json
  packages/client/pages/index.tsx
  packages/client/yarn.lock
  packages/server/.env.default
  packages/server/.vscode/launch.json
  packages/server/package.json
  packages/server/src/common/interceptors/responseWithAllowOriginInterceptor.ts
  packages/server/src/config/config.service.ts
  packages/server/src/main.ts
  packages/server/src/migration/1622718115030-default-base-entity.ts
  packages/server/src/modules/account/model.ts
  packages/server/src/modules/account/service.ts
  packages/server/src/modules/auth/controller.ts
  packages/server/src/modules/auth/index.ts
  packages/server/src/modules/auth/interfaces/requestWithUser.ts
  packages/server/src/modules/auth/service.ts
  packages/server/src/modules/auth/strategies/jwt.ts
  packages/server/src/modules/auth/types.ts
  packages/server/src/modules/base/base.entity.ts
  packages/server/src/modules/comment-reactions/entities/comment-reaction.entity.ts
  packages/server/src/modules/comments/entities/comment.entity.ts
  packages/server/src/modules/course/model.ts
  packages/server/src/modules/example/model.ts
  packages/server/src/modules/role/index.ts
  packages/server/src/modules/role/model.ts
  packages/server/src/modules/role/service.ts
  packages/server/src/modules/sub-lines/entities/sub-line.entity.ts
  packages/server/src/modules/subtitles/entities/subtitle.entity.ts
  packages/server/src/modules/user/model.ts
  packages/server/src/modules/video/model.ts
  packages/server/src/scripts/start-local-db-unix.sh
  packages/server/src/scripts/start.sh
  packages/server/src/seeds/roleSeeder.ts
  packages/server/tsconfig.json
  packages/server/yarn.lock
Labels: backend, enhancement

#96 Feature/cm 92 upload video to s3
  packages/cms/package.json
  packages/cms/src/App.js
  packages/cms/src/axios.js
  packages/cms/yarn.lock
  packages/server/package.json
  packages/server/src/common/exceptions/all-exception.filter.ts
  packages/server/src/migration/1622822936510-change-url-of-video-nullable.ts
  packages/server/src/modules/auth/guards/jwt.ts
  packages/server/src/modules/auth/guards/role.ts
  packages/server/src/modules/auth/strategies/jwt.ts
  packages/server/src/modules/course/controller.ts
  packages/server/src/modules/file-upload/file-upload.interface.ts
  packages/server/src/modules/file-upload/strategies/s3.ts
  packages/server/src/modules/user/controller.ts
  packages/server/src/modules/user/index.ts
  packages/server/src/modules/video/controller.ts
  packages/server/src/modules/video/dto/create-video.dto.ts
  packages/server/src/modules/video/index.ts
  packages/server/src/modules/video/model.ts
  packages/server/src/modules/video/service.ts
  packages/server/yarn.lock
Labels: backend

#99 upload file to s3
  packages/server/.env.default
  packages/server/src/common/enums/file-upload-type.enum.ts
  packages/server/src/modules/file-upload/controller.ts
  packages/server/src/modules/file-upload/dto/file-upload.dto.ts
  packages/server/src/modules/file-upload/file-upload.interface.ts
  packages/server/src/modules/file-upload/index.ts
  packages/server/src/modules/file-upload/strategies/s3.ts
  packages/server/src/modules/index.ts
  packages/server/src/modules/video/controller.ts
  packages/server/src/modules/video/dto/create-video.dto.ts
  packages/server/src/modules/video/model.ts
  packages/server/src/modules/video/service.ts
Labels: backend

#101 add feature get all file from s3
  packages/server/src/modules/file-upload/controller.ts
  packages/server/src/modules/file-upload/file-upload.interface.ts
  packages/server/src/modules/file-upload/strategies/s3.ts
Labels: backend
