Repository OngDev/course-manager, pull requests merged in 2021-05, with the labels that each got.

#36 Feature/cm 20 mockdata
  packages/client/mock/api.ts
  packages/client/mock/video.ts
  packages/client/package.json
  packages/client/src/components/Video/VideoItem/index.tsx
  packages/client/src/components/Video/VideoList/index.tsx
  packages/client/src/interfaces/video.ts
  packages/client/src/pages/index.tsx
  packages/client/src/styles/video.css
Labels: enhancement, frontend

#34 Init course model
  packages/server/src/migration/1620141780850-init-course-model.ts
  packages/server/src/modules/course/controller.ts
  packages/server/src/modules/course/dto.ts
  packages/server/src/modules/course/index.ts
  packages/server/src/modules/course/model.ts
  packages/server/src/modules/course/service.ts
  packages/server/src/modules/index.ts
Labels: backend, enhancement

#37 docs(style-guide): setup, basic style guide
  CourseManager.code-workspace
  docs/style-guide.md
Labels: frontend

#38 Feature/cm 4 init video model
  packages/server/src/migration/1620322511364-init-video-model.ts
  packages/server/src/migration/1620398650234-init-video-model.ts
  packages/server/src/modules/course/model.ts
  packages/server/src/modules/index.ts
  packages/server/src/modules/video/controller.spec.ts
  packages/server/src/modules/video/controller.ts
  packages/server/src/modules/video/dto/create-video.dto.ts
  packages/server/src/modules/video/dto/update-video.dto.ts
  packages/server/src/modules/video/entities/video.entity.ts
  packages/server/src/modules/video/index.ts
  packages/server/src/modules/video/service.spec.ts
  packages/server/src/modules/video/service.ts
Labels: backend, enhancement

#39 add subtitles module
  packages/server/src/migration/1620197890942-init-subtitle-model.ts
  packages/server/src/modules/index.ts
  packages/server/src/modules/subtitles/dto/create-subtitle.dto.ts
  packages/server/src/modules/subtitles/dto/update-subtitle.dto.ts
  packages/server/src/modules/subtitles/entities/subtitle.entity.ts
  packages/server/src/modules/subtitles/subtitles.controller.spec.ts
  packages/server/src/modules/subtitles/subtitles.controller.ts
  packages/server/src/modules/subtitles/subtitles.module.ts
  packages/server/src/modules/subtitles/subtitles.service.spec.ts
  packages/server/src/modules/subtitles/subtitles.service.ts
Labels: backend, enhancement

#41 add comment module
  packages/server/src/migration/1620226666710-init-comment-model.ts
  packages/server/src/modules/comments/comments.controller.spec.ts
  packages/server/src/modules/comments/comments.controller.ts
  packages/server/src/modules/comments/comments.module.ts
  packages/server/src/modules/comments/comments.service.spec.ts
  packages/server/src/modules/comments/comments.service.ts
  packages/server/src/modules/comments/dto/create-comment.dto.ts
  packages/server/src/modules/comments/dto/update-comment.dto.ts
  packages/server/src/modules/comments/entities/comment.entity.ts
  packages/server/src/modules/index.ts
Labels: backend

#40 init sub-line model
  packages/server/src/migration/1620225079680-init-sub-line-model.ts
  packages/server/src/modules/index.ts
  packages/server/src/modules/sub-lines/dto/create-sub-line.dto.ts
  packages/server/src/modules/sub-lines/dto/update-sub-line.dto.ts
  packages/server/src/modules/sub-lines/entities/sub-line.entity.ts
  packages/server/src/modules/sub-lines/sub-lines.controller.spec.ts
  packages/server/src/modules/sub-lines/sub-lines.controller.ts
  packages/server/src/modules/sub-lines/sub-lines.module.ts
  packages/server/src/modules/sub-lines/sub-lines.service.spec.ts
  packages/server/src/modules/sub-lines/sub-lines.service.ts
Labels: backend

#42 add comment reaction model
  packages/server/src/common/enums/reaction-type.enum.ts
  packages/server/src/migration/1620228218954-init-comment-reaction-model.ts
  packages/server/src/modules/comment-reactions/comment-reactions.controller.spec.ts
  packages/server/src/modules/comment-reactions/comment-reactions.controller.ts
  packages/server/src/modules/comment-reactions/comment-reactions.module.ts
  packages/server/src/modules/comment-reactions/comment-reactions.service.spec.ts
  packages/server/src/modules/comment-reactions/comment-reactions.service.ts
  packages/server/src/modules/comment-reactions/dto/create-comment-reaction.dto.ts
  packages/server/src/modules/comment-reactions/dto/update-comment-reaction.dto.ts
  packages/server/src/modules/comment-reactions/entities/comment-reaction.entity.ts
  packages/server/src/modules/course/dto/create-course.dto.ts
  packages/server/src/modules/course/dto/update-course.dto.ts
  packages/server/src/modules/index.ts
Labels: backend

#52 docs(style-guide): fix typo (#50)
  docs/style-guide.md
Labels: frontend

#62 add exception filter
  packages/server/src/common/exceptions/all-exception.filter.ts
  packages/server/src/common/helpers/catch-error.ts
Labels: backend

#59 :tada: feature/CM-55-course-service-and-controller
  packages/server/src/modules/course/controller.ts
  packages/server/src/modules/course/dto/update-course.dto.ts
  packages/server/src/modules/course/model.ts
  packages/server/src/modules/course/service.ts
  packages/server/src/modules/video/dto/create-video.dto.ts
  packages/server/src/modules/video/model.ts
Labels: backend

#66 rename comment and subtitle dto
  packages/server/src/main.ts
  packages/server/src/modules/comment-reactions/comment-reactions.controller.ts
  packages/server/src/modules/comment-reactions/comment-reactions.service.ts
  packages/server/src/modules/comment-reactions/dto/create-comment-reaction.dto.ts
  packages/server/src/modules/comment-reactions/dto/update-comment-reaction.dto.ts
  packages/server/src/modules/comments/comments.controller.ts
  packages/server/src/modules/comments/comments.service.ts
  packages/server/src/modules/comments/dto/create-comment.dto.ts
  packages/server/src/modules/comments/dto/update-comment.dto.ts
  packages/server/src/modules/sub-lines/dto/create-sub-line.dto.ts
  packages/server/src/modules/sub-lines/dto/update-sub-line.dto.ts
  packages/server/src/modules/sub-lines/sub-lines.controller.ts
  packages/server/src/modules/sub-lines/sub-lines.service.ts
  packages/server/src/modules/subtitles/dto/create-subtitle.dto.ts
  packages/server/src/modules/subtitles/dto/update-subtitle.dto.ts
  packages/server/src/modules/subtitles/subtitles.controller.ts
  packages/server/src/modules/subtitles/subtitles.service.ts
Labels: backend

#73 add CRUD subtitles
  packages/server/.env.default
  packages/server/src/common/dto/pagination-query.dto.ts
  packages/server/src/modules/comment-reactions/comment-reactions.controller.ts
  packages/server/src/modules/comments/comments.controller.ts
  packages/server/src/modules/sub-lines/sub-lines.controller.ts
  packages/server/src/modules/subtitles/subtitles.controller.ts
  packages/server/src/modules/subtitles/subtitles.module.ts
  packages/server/src/modules/subtitles/subtitles.service.ts
Labels: backend

#75 Feature/stream video
  packages/server/package.json
  packages/server/src/migration/1620485415609-add-association-video-subtitle.ts
  packages/server/src/modules/course/controller.ts
  packages/server/src/modules/course/service.ts
  packages/server/src/modules/stream/controller.ts
  packages/server/src/modules/stream/index.ts
  packages/server/src/modules/stream/types.ts
  packages/server/src/modules/stream/utils.ts
  packages/server/src/modules/sub-lines/sub-lines.module.ts
  packages/server/src/modules/video/controller.ts
  packages/server/src/modules/video/dto/update-video.dto.ts
  packages/server/src/modules/video/index.ts
  packages/server/src/modules/video/service.ts
  packages/server/yarn.lock
Labels: backend, enhancement

#79 Create ui cms page
  packages/cms/src/assets/icon/home.png
  packages/cms/src/assets/icon/logout.png
  packages/cms/src/assets/icon/messages.png
  packages/cms/src/assets/icon/progress.png
  packages/cms/src/assets/icon/setting.png
  packages/cms/src/components/SiderBar/SiderBar.tsx
  packages/cms/src/pages/cms/cms.css
  packages/cms/src/pages/cms/cms.tsx
  packages/cms/src/pages/index.css
  packages/cms/src/pages/index.tsx
  packages/cms/src/styles/siderbar.css
Labels: CMS, enhancement, frontend

#85 Feature/use passport instead of keycloak
  packages/server/.env.default
  packages/server/package.json
  packages/server/src/common/helpers/catch-error.ts
  packages/server/src/config/config.service.ts
  packages/server/src/migration/1622119780070-init-user-roles.ts
  packages/server/src/modules/account/index.ts
  packages/server/src/modules/account/model.ts
  packages/server/src/modules/account/service.ts
  packages/server/src/modules/auth/controller.ts
  packages/server/src/modules/auth/guards/jwt.ts
  packages/server/src/modules/auth/guards/local.ts
  packages/server/src/modules/auth/index.ts
  packages/server/src/modules/auth/service.ts
  packages/server/src/modules/auth/strategies/jwt.ts
  packages/server/src/modules/auth/strategies/local.ts
  packages/server/src/modules/auth/types.ts
  packages/server/src/modules/auth/utils.ts
  packages/server/src/modules/index.ts
  packages/server/src/modules/role/model.ts
  packages/server/src/modules/user/index.ts
  packages/server/src/modules/user/model.ts
  packages/server/src/modules/user/types.ts
  packages/server/tsconfig.json
  packages/server/yarn.lock
Labels: backend, enhancement

#60 :tada: feature/CM-56-video-service-and-controller
  packages/server/src/modules/video/controller.ts
  packages/server/src/modules/video/dto/create-video.dto.ts
  packages/server/src/modules/video/service.ts
Labels: backend

#72 :tada: refactor/CM-71-return-exactly-value-type-course-service
  packages/server/src/modules/course/controller.ts
  packages/server/src/modules/course/service.ts
Labels: backend

#81 add comment services and controllers
  packages/server/src/modules/comments/comments.controller.ts
  packages/server/src/modules/comments/comments.module.ts
  packages/server/src/modules/comments/comments.service.ts
  packages/server/src/modules/comments/dto/comment.dto.ts
  packages/server/src/modules/comments/dto/create-comment.dto.ts
  packages/server/src/modules/video/index.ts
Labels: backend

#80 add sub-line services and controllers
  packages/server/src/migration/1621609251172-add-association-sub-line-and-subtile.ts
  packages/server/src/modules/sub-lines/dto/create-sub-line.dto.ts
  packages/server/src/modules/sub-lines/dto/sub-line.dto.ts
  packages/server/src/modules/sub-lines/entities/sub-line.entity.ts
  packages/server/src/modules/sub-lines/sub-lines.controller.ts
  packages/server/src/modules/sub-lines/sub-lines.module.ts
  packages/server/src/modules/sub-lines/sub-lines.service.ts
  packages/server/src/modules/subtitles/entities/subtitle.entity.ts
  packages/server/src/modules/subtitles/subtitles.module.ts
  packages/server/src/modules/video/index.ts
Labels: backend

#83 Init Account Module
  packages/server/src/modules/account/controller.ts
  packages/server/src/modules/account/dto/account-creation.dto.ts
  packages/server/src/modules/account/dto/account-updation.dto.ts
  packages/server/src/modules/account/dto/account.ts
  packages/server/src/modules/account/index.ts
  packages/server/src/modules/account/mapper.ts
  packages/server/src/modules/account/service.ts
  packages/server/src/modules/auth/service.ts
  packages/server/src/modules/course/controller.ts
Labels: backend

#88 Feature/client register modal
  CourseManager.code-workspace
  packages/client/.eslintrc
  packages/client/components/FormItem/index.module.css
  packages/client/components/FormItem/index.tsx
  packages/client/components/Register/index.module.css
  packages/client/components/Register/index.tsx
  packages/client/package.json
  packages/client/pages/index.module.css
  packages/client/pages/index.tsx
  packages/client/public/icons/error-icon.svg
  packages/client/public/icons/valid-icon.svg
  packages/client/styles/Modal.module.css
  packages/client/styles/globals.css
  packages/client/yarn.lock
  packages/cms/src/layouts/index.css
  packages/cms/src/pages/index.css
Labels: enhancement, frontend

#87 Feature/cm 70 comment reaction services and controllers
  packages/server/src/common/exceptions/all-exception.filter.ts
  packages/server/src/migration/1622119780070-init-user-roles.ts
  packages/server/src/migration/1622214325342-init-user-roles.ts
  packages/server/src/migration/1622216160962-add-association-comment-and-comment-reaction.ts
  packages/server/src/modules/auth/controller.ts
  packages/server/src/modules/auth/index.ts
  packages/server/src/modules/comment-reactions/comment-reactions.controller.ts
  packages/server/src/modules/comment-reactions/comment-reactions.module.ts
  packages/server/src/modules/comment-reactions/comment-reactions.service.ts
  packages/server/src/modules/comment-reactions/dto/comment-reaction.dto.ts
  packages/server/src/modules/comment-reactions/dto/create-comment-reaction.dto.ts
  packages/server/src/modules/comment-reactions/dto/update-comment-reaction.dto.ts
  packages/server/src/modules/comment-reactions/entities/comment-reaction.entity.ts
  packages/server/src/modules/comments/entities/comment.entity.ts
  packages/server/src/modules/index.ts
  packages/server/src/modules/sub-lines/dto/create-sub-line.dto.ts
Labels: backend
